name: example
on: push

env:
  NODE_VERSION: 16.15.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - name: fab build
      run: |
        npm install
        npx fab init
        npm run build:fab
    - name: remove old config
      run: |
        rm fab.config.json5
    - name: get new Fab config
      uses: actions/checkout@v3
      with:
        repository: Jooliashi/fab-config
        path: fab.config.json5
    - name: create .env
      run: |
        touch .env
        echo CF_WORKERS_ACCOUNT_ID=${{ secrets.CF_WORKERS_ACCOUNT_ID }} >> .env
        echo CF_WORKERS_API_TOKEN=${{ secrets.CF_WORKERS_API_TOKEN }} >> .env
        echo S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }} >> .env
        echo S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }} >> .env
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}


